// Maps country names (as used by react-simple-maps) to ISO country codes
// and flag emojis
export const countryData: Record<string, { code: string; flag: string; continent: string }> = {
  "Afghanistan": { code: "AF", flag: "🇦🇫", continent: "Asia" },
  "Albania": { code: "AL", flag: "🇦🇱", continent: "Europe" },
  "Algeria": { code: "DZ", flag: "🇩🇿", continent: "Africa" },
  "Angola": { code: "AO", flag: "🇦🇴", continent: "Africa" },
  "Argentina": { code: "AR", flag: "🇦🇷", continent: "South America" },
  "Armenia": { code: "AM", flag: "🇦🇲", continent: "Asia" },
  "Australia": { code: "AU", flag: "🇦🇺", continent: "Oceania" },
  "Austria": { code: "AT", flag: "🇦🇹", continent: "Europe" },
  "Azerbaijan": { code: "AZ", flag: "🇦🇿", continent: "Asia" },
  "Bahrain": { code: "BH", flag: "🇧🇭", continent: "Asia" },
  "Bangladesh": { code: "BD", flag: "🇧🇩", continent: "Asia" },
  "Belarus": { code: "BY", flag: "🇧🇾", continent: "Europe" },
  "Belgium": { code: "BE", flag: "🇧🇪", continent: "Europe" },
  "Belize": { code: "BZ", flag: "🇧🇿", continent: "North America" },
  "Benin": { code: "BJ", flag: "🇧🇯", continent: "Africa" },
  "Bhutan": { code: "BT", flag: "🇧🇹", continent: "Asia" },
  "Bolivia": { code: "BO", flag: "🇧🇴", continent: "South America" },
  "Bosnia and Herz.": { code: "BA", flag: "🇧🇦", continent: "Europe" },
  "Botswana": { code: "BW", flag: "🇧🇼", continent: "Africa" },
  "Brazil": { code: "BR", flag: "🇧🇷", continent: "South America" },
  "Brunei": { code: "BN", flag: "🇧🇳", continent: "Asia" },
  "Bulgaria": { code: "BG", flag: "🇧🇬", continent: "Europe" },
  "Burkina Faso": { code: "BF", flag: "🇧🇫", continent: "Africa" },
  "Burundi": { code: "BI", flag: "🇧🇮", continent: "Africa" },
  "Cambodia": { code: "KH", flag: "🇰🇭", continent: "Asia" },
  "Cameroon": { code: "CM", flag: "🇨🇲", continent: "Africa" },
  "Canada": { code: "CA", flag: "🇨🇦", continent: "North America" },
  "Central African Rep.": { code: "CF", flag: "🇨🇫", continent: "Africa" },
  "Chad": { code: "TD", flag: "🇹🇩", continent: "Africa" },
  "Chile": { code: "CL", flag: "🇨🇱", continent: "South America" },
  "China": { code: "CN", flag: "🇨🇳", continent: "Asia" },
  "Colombia": { code: "CO", flag: "🇨🇴", continent: "South America" },
  "Congo": { code: "CG", flag: "🇨🇬", continent: "Africa" },
  "Dem. Rep. Congo": { code: "CD", flag: "🇨🇩", continent: "Africa" },
  "Costa Rica": { code: "CR", flag: "🇨🇷", continent: "North America" },
  "Côte d'Ivoire": { code: "CI", flag: "🇨🇮", continent: "Africa" },
  "Croatia": { code: "HR", flag: "🇭🇷", continent: "Europe" },
  "Cuba": { code: "CU", flag: "🇨🇺", continent: "North America" },
  "Cyprus": { code: "CY", flag: "🇨🇾", continent: "Europe" },
  "Czechia": { code: "CZ", flag: "🇨🇿", continent: "Europe" },
  "Denmark": { code: "DK", flag: "🇩🇰", continent: "Europe" },
  "Djibouti": { code: "DJ", flag: "🇩🇯", continent: "Africa" },
  "Dominican Rep.": { code: "DO", flag: "🇩🇴", continent: "North America" },
  "Ecuador": { code: "EC", flag: "🇪🇨", continent: "South America" },
  "Egypt": { code: "EG", flag: "🇪🇬", continent: "Africa" },
  "El Salvador": { code: "SV", flag: "🇸🇻", continent: "North America" },
  "Eritrea": { code: "ER", flag: "🇪🇷", continent: "Africa" },
  "Estonia": { code: "EE", flag: "🇪🇪", continent: "Europe" },
  "Ethiopia": { code: "ET", flag: "🇪🇹", continent: "Africa" },
  "Finland": { code: "FI", flag: "🇫🇮", continent: "Europe" },
  "France": { code: "FR", flag: "🇫🇷", continent: "Europe" },
  "Gabon": { code: "GA", flag: "🇬🇦", continent: "Africa" },
  "Gambia": { code: "GM", flag: "🇬🇲", continent: "Africa" },
  "Georgia": { code: "GE", flag: "🇬🇪", continent: "Asia" },
  "Germany": { code: "DE", flag: "🇩🇪", continent: "Europe" },
  "Ghana": { code: "GH", flag: "🇬🇭", continent: "Africa" },
  "Greece": { code: "GR", flag: "🇬🇷", continent: "Europe" },
  "Guatemala": { code: "GT", flag: "🇬🇹", continent: "North America" },
  "Guinea": { code: "GN", flag: "🇬🇳", continent: "Africa" },
  "Guinea-Bissau": { code: "GW", flag: "🇬🇼", continent: "Africa" },
  "Haiti": { code: "HT", flag: "🇭🇹", continent: "North America" },
  "Honduras": { code: "HN", flag: "🇭🇳", continent: "North America" },
  "Hungary": { code: "HU", flag: "🇭🇺", continent: "Europe" },
  "Iceland": { code: "IS", flag: "🇮🇸", continent: "Europe" },
  "India": { code: "IN", flag: "🇮🇳", continent: "Asia" },
  "Indonesia": { code: "ID", flag: "🇮🇩", continent: "Asia" },
  "Iran": { code: "IR", flag: "🇮🇷", continent: "Asia" },
  "Iraq": { code: "IQ", flag: "🇮🇶", continent: "Asia" },
  "Ireland": { code: "IE", flag: "🇮🇪", continent: "Europe" },
  "Israel": { code: "IL", flag: "🇮🇱", continent: "Asia" },
  "Italy": { code: "IT", flag: "🇮🇹", continent: "Europe" },
  "Jamaica": { code: "JM", flag: "🇯🇲", continent: "North America" },
  "Japan": { code: "JP", flag: "🇯🇵", continent: "Asia" },
  "Jordan": { code: "JO", flag: "🇯🇴", continent: "Asia" },
  "Kazakhstan": { code: "KZ", flag: "🇰🇿", continent: "Asia" },
  "Kenya": { code: "KE", flag: "🇰🇪", continent: "Africa" },
  "Kosovo": { code: "XK", flag: "🇽🇰", continent: "Europe" },
  "Kuwait": { code: "KW", flag: "🇰🇼", continent: "Asia" },
  "Kyrgyzstan": { code: "KG", flag: "🇰🇬", continent: "Asia" },
  "Laos": { code: "LA", flag: "🇱🇦", continent: "Asia" },
  "Latvia": { code: "LV", flag: "🇱🇻", continent: "Europe" },
  "Lebanon": { code: "LB", flag: "🇱🇧", continent: "Asia" },
  "Lesotho": { code: "LS", flag: "🇱🇸", continent: "Africa" },
  "Liberia": { code: "LR", flag: "🇱🇷", continent: "Africa" },
  "Libya": { code: "LY", flag: "🇱🇾", continent: "Africa" },
  "Lithuania": { code: "LT", flag: "🇱🇹", continent: "Europe" },
  "Luxembourg": { code: "LU", flag: "🇱🇺", continent: "Europe" },
  "Madagascar": { code: "MG", flag: "🇲🇬", continent: "Africa" },
  "Malawi": { code: "MW", flag: "🇲🇼", continent: "Africa" },
  "Malaysia": { code: "MY", flag: "🇲🇾", continent: "Asia" },
  "Mali": { code: "ML", flag: "🇲🇱", continent: "Africa" },
  "Mauritania": { code: "MR", flag: "🇲🇷", continent: "Africa" },
  "Mexico": { code: "MX", flag: "🇲🇽", continent: "North America" },
  "Moldova": { code: "MD", flag: "🇲🇩", continent: "Europe" },
  "Mongolia": { code: "MN", flag: "🇲🇳", continent: "Asia" },
  "Montenegro": { code: "ME", flag: "🇲🇪", continent: "Europe" },
  "Morocco": { code: "MA", flag: "🇲🇦", continent: "Africa" },
  "Mozambique": { code: "MZ", flag: "🇲🇿", continent: "Africa" },
  "Myanmar": { code: "MM", flag: "🇲🇲", continent: "Asia" },
  "Namibia": { code: "NA", flag: "🇳🇦", continent: "Africa" },
  "Nepal": { code: "NP", flag: "🇳🇵", continent: "Asia" },
  "Netherlands": { code: "NL", flag: "🇳🇱", continent: "Europe" },
  "New Zealand": { code: "NZ", flag: "🇳🇿", continent: "Oceania" },
  "Nicaragua": { code: "NI", flag: "🇳🇮", continent: "North America" },
  "Niger": { code: "NE", flag: "🇳🇪", continent: "Africa" },
  "Nigeria": { code: "NG", flag: "🇳🇬", continent: "Africa" },
  "North Korea": { code: "KP", flag: "🇰🇵", continent: "Asia" },
  "North Macedonia": { code: "MK", flag: "🇲🇰", continent: "Europe" },
  "Norway": { code: "NO", flag: "🇳🇴", continent: "Europe" },
  "Oman": { code: "OM", flag: "🇴🇲", continent: "Asia" },
  "Pakistan": { code: "PK", flag: "🇵🇰", continent: "Asia" },
  "Palestine": { code: "PS", flag: "🇵🇸", continent: "Asia" },
  "Panama": { code: "PA", flag: "🇵🇦", continent: "North America" },
  "Papua New Guinea": { code: "PG", flag: "🇵🇬", continent: "Oceania" },
  "Paraguay": { code: "PY", flag: "🇵🇾", continent: "South America" },
  "Peru": { code: "PE", flag: "🇵🇪", continent: "South America" },
  "Philippines": { code: "PH", flag: "🇵🇭", continent: "Asia" },
  "Poland": { code: "PL", flag: "🇵🇱", continent: "Europe" },
  "Portugal": { code: "PT", flag: "🇵🇹", continent: "Europe" },
  "Qatar": { code: "QA", flag: "🇶🇦", continent: "Asia" },
  "Romania": { code: "RO", flag: "🇷🇴", continent: "Europe" },
  "Russia": { code: "RU", flag: "🇷🇺", continent: "Europe" },
  "Rwanda": { code: "RW", flag: "🇷🇼", continent: "Africa" },
  "Saudi Arabia": { code: "SA", flag: "🇸🇦", continent: "Asia" },
  "Senegal": { code: "SN", flag: "🇸🇳", continent: "Africa" },
  "Serbia": { code: "RS", flag: "🇷🇸", continent: "Europe" },
  "Sierra Leone": { code: "SL", flag: "🇸🇱", continent: "Africa" },
  "Slovakia": { code: "SK", flag: "🇸🇰", continent: "Europe" },
  "Slovenia": { code: "SI", flag: "🇸🇮", continent: "Europe" },
  "Somalia": { code: "SO", flag: "🇸🇴", continent: "Africa" },
  "South Africa": { code: "ZA", flag: "🇿🇦", continent: "Africa" },
  "South Korea": { code: "KR", flag: "🇰🇷", continent: "Asia" },
  "South Sudan": { code: "SS", flag: "🇸🇸", continent: "Africa" },
  "Spain": { code: "ES", flag: "🇪🇸", continent: "Europe" },
  "Sri Lanka": { code: "LK", flag: "🇱🇰", continent: "Asia" },
  "Sudan": { code: "SD", flag: "🇸🇩", continent: "Africa" },
  "Suriname": { code: "SR", flag: "🇸🇷", continent: "South America" },
  "Sweden": { code: "SE", flag: "🇸🇪", continent: "Europe" },
  "Switzerland": { code: "CH", flag: "🇨🇭", continent: "Europe" },
  "Syria": { code: "SY", flag: "🇸🇾", continent: "Asia" },
  "Taiwan": { code: "TW", flag: "🇹🇼", continent: "Asia" },
  "Tajikistan": { code: "TJ", flag: "🇹🇯", continent: "Asia" },
  "Tanzania": { code: "TZ", flag: "🇹🇿", continent: "Africa" },
  "Thailand": { code: "TH", flag: "🇹🇭", continent: "Asia" },
  "Timor-Leste": { code: "TL", flag: "🇹🇱", continent: "Asia" },
  "Togo": { code: "TG", flag: "🇹🇬", continent: "Africa" },
  "Tunisia": { code: "TN", flag: "🇹🇳", continent: "Africa" },
  "Turkey": { code: "TR", flag: "🇹🇷", continent: "Asia" },
  "Turkmenistan": { code: "TM", flag: "🇹🇲", continent: "Asia" },
  "Uganda": { code: "UG", flag: "🇺🇬", continent: "Africa" },
  "Ukraine": { code: "UA", flag: "🇺🇦", continent: "Europe" },
  "United Arab Emirates": { code: "AE", flag: "🇦🇪", continent: "Asia" },
  "United Kingdom": { code: "GB", flag: "🇬🇧", continent: "Europe" },
  "United States of America": { code: "US", flag: "🇺🇸", continent: "North America" },
  "Uruguay": { code: "UY", flag: "🇺🇾", continent: "South America" },
  "Uzbekistan": { code: "UZ", flag: "🇺🇿", continent: "Asia" },
  "Venezuela": { code: "VE", flag: "🇻🇪", continent: "South America" },
  "Vietnam": { code: "VN", flag: "🇻🇳", continent: "Asia" },
  "Yemen": { code: "YE", flag: "🇾🇪", continent: "Asia" },
  "Zambia": { code: "ZM", flag: "🇿🇲", continent: "Africa" },
  "Zimbabwe": { code: "ZW", flag: "🇿🇼", continent: "Africa" },
};

// Reverse lookup: country_code → name
export const codeToName: Record<string, string> = Object.fromEntries(
  Object.entries(countryData).map(([name, { code }]) => [code, name])
);

export function getFlag(countryName: string): string {
  return countryData[countryName]?.flag ?? "🏳️";
}

export function nameToCode(countryName: string): string | null {
  return countryData[countryName]?.code ?? null;
}

export const continentTotals: Record<string, number> = {
  "Africa": 54, "Asia": 48, "Europe": 44, "North America": 23,
  "South America": 12, "Oceania": 14,
};
